on right click with firework rocket:
    if chestplate of player is elytra:
        if player is not on the ground:
            if {hax.fastelytra::*} contains player:
                set gliding of player to true'

command /fastelytra:
    permission: skript.HAX
    trigger: 
        if {hax.fastelytra::*} contains player:
            remove player from {hax.fastelytra::*}
            send "&6&lHAX &r&8» &aFastelytra has been disabled!" to player
        else:
            add player to {hax.fastelytra::*}
            send "&6&lHAX &r&8» &aFastelytra has been enabled!" to player