on right click with firework rocket:
    if chestplate of player is elytra:
        if player is not on the ground:
            if {hax.fastelytra.%player%} is "enabled":
                set gliding of player to true

on damage of player:
    if victim is player:
        if victim's health - final damage <= 0:
            if victim's offhand item is totem of undying:
                wait 1 tick
                if victim's inventory contains totem of undying:
                    if {hax.instatotem.%victim%} is "enabled":
                        remove 1 of totem of undying from victim's inventory
                        set victim's offhand item to totem of undying

on damage:
    if attacker's tool is mace:
        if gliding of attacker is true:
            if {hax.elytramace.%attacker%} is "enabled":
                set gliding of attacker to false
                wait 1 tick
                set gliding of attacker to true

on damage:
    if attacker's tool is mace:
        if {hax.alwaysslam.%attacker%} is "enabled":
            if attacker's fall distance < 2:
                set attacker's fall distance to 2


import:
    org.bukkit.Material
    org.bukkit.block.data.BlockData

every second:
    loop all players:
        if {hax.xray.%loop-player%} is "enabled":
            set {_p} to loop-player

            loop blocks in radius 10 around {_p}:
                if loop-block is stone:
                    set {_loc} to location of loop-block

                    set {_glass} to Material.LIGHT_GRAY_STAINED_GLASS.createBlockData()

                    {_p}.sendBlockChange({_loc}, {_glass})
                if loop-block is deepslate:
                    set {_loc} to location of loop-block

                    set {_glass} to Material.GRAY_STAINED_GLASS.createBlockData()

                    {_p}.sendBlockChange({_loc}, {_glass})