on load:
    delete {hax.list::*}
    add "fastelytra" to {hax.list::*}
    add "instatotem" to {hax.list::*}
    add "xray" to {hax.list::*}
    add "elytramace" to {hax.list::*}
    add "alwaysslam" to {hax.list::*}   
    loop {hax.list::*}:
        loop all players:
            if {hax.%loop-value-1%.%loop-player%} is not set:
                set {hax.%loop-value-1%.%loop-player%} to "disabled"

on join:
    loop {hax.list::*}:
        if {hax.%loop-value%.%player%} is not set:
            set {hax.%loop-value%.%player%} to "disabled"


command /HAX [<text>]:
    permission: skript.HAX
    trigger: 
        if {hax.list::*} contains arg-1:
            if {hax.%arg-1%.%player%} is "enabled":
                set {hax.%arg-1%.%player%} to "disabled"
                send "&6&lHAX &r&8» &a%arg-1% has been disabled!" to player
            else:
                set {hax.%arg-1%.%player%} to "enabled"
                send "&6&lHAX &r&8» &a%arg-1% has been enabled!" to player
            stop
        
        send "&6&lHAX &r&8» &rAvailable HAX:" to player
        loop {hax.list::*}:
            send "&6&lHAX &r&8» &r%{hax.list::%loop-index%}% - %{hax.%{hax.list::%loop-index%}%.%player%}%" to player
       
on tab complete of "/hax":
    set tab completions for position 1 to {hax.list::*}
