command /lobby:
    trigger:
        if player's world contains "LifeSteal":
            set {lastloc.%player%.LifeSteal} to player's location
        else:
            set {lastloc.%player%.%player's world%} to player's location
        teleport player to location(0.5, 21, 0.5, world "Lobby")

command /hub:
    trigger: 
        execute player command "/lobby"

command /worldswitch [<text>] [<player>]:
    trigger:
        if arg-1 is "LifeSteal":
            if {lastloc.%player%.LifeSteal} is set:
                teleport player to {lastloc.%player%.LifeSteal}
            else:
                execute console command "/mvtp %player% LifeSteal_lobby"
            stop
        if {lastloc.%player%.%arg-1%} is set:
            teleport player to {lastloc.%player%.%arg-1%}
        else:
            execute console command "/mvtp %player% %arg-1%"

on tab complete of "/worldswitch":
    set tab completions for position 1 to all worlds