on join:
    wait 3 tick
    set {_b} to player's client brand
    set {client.%player%} to "java"
    loop {eaglerbrands::*}:
        if loop-value contains {_b}:
            set {client.%player%} to "eagler"

command /clientrefresh:
    trigger:
        set {_b} to player's client brand
        set {client.%player%} to "java"
        loop {eaglerbrands::*}:
            if loop-value contains {_b}:
                set {client.%player%} to "eagler"
        send "refreshed client: %{client.%player%}%"

on leave:
    delete {client.%player%}

command /client:
    trigger:
        set {_brand} to player's client brand
        if {_brand} is not set:
            set {_brand} to "unknown"
        send "Your current client: %{_brand}%" to player
        send "java/eagler: %{client.%player%}%" to player
        send "if this is wrong please use /clientrefresh" to player

on load:
    delete {eaglerbrands::*}
    add "TuffClient" to {eaglerbrands::*}
    add "Eagler" to {eaglerbrands::*}