on spawn:
    if spawn reason is not natural:
        stop
    loop all entities:
        if loop-entity is not a player:
            if loop-entity is not a item:
                add 1 to {_e}
    if {_e} >= 30:
        cancel event

command /clearlag:
    permission: op
    trigger:
        loop all entities:
            if loop-entity is not a player
            if loop-entity is not tamed
            if name of loop-entity is not set
            if loop-entity is not a villager
            if loop-entity is not an armor stand
            kill loop-entity

        broadcast "&r&d&lClearlag &r&8»&r &aCleared all wild mobs."