on spawn:
    if spawn reason is not natural:
        stop
    loop all entities:
        if loop-entity is not a player:
            if loop-entity is not a item:
                add 1 to {_e}
    if {_e} >= 30:
        cancel event

command /fucklag:
    trigger:
        loop all entities:
            if loop-entity is not a player:
                if loop-entity is not a villager:
                    kill loop-entity