function BuyItem(p: player, item: item):
    set {_s} to uncolored {_sec}
    set {_i} to chest inventory with 5 rows named "&r&8Server Shop » buy %{_item}%"

    set {_lore::*} to lore of {_item}
    set {_price::*} to {_lore::1} split at "$"
    set {_pricep} to {_price::2}
        
    set {_id} to 0
    loop 54 times:
        set slot {_id} of {_i} to gray stained glass pane named ""
        add 1 to {_id}

    set {_id} to 45
    loop 9 times:
        set slot {_id} of {_i} to light gray stained glass pane named ""
        add 1 to {_id}

    set slot 36 of {_i} to {_p}'s skull named "&r&f%{_p}%" with lore "&aBalance: &r&e%{_p}'s balance%"
    set slot 44 of {_i} to barrier named "&r&cBack"
    set {_items} to {_item}
    clear lore of {_items}
    set slot 22 of {_i} to {_items}
    set slot 13 of {_i} to emerald named "%{_pricep}%"
    set {_price} to {_pricep} * amount of {_item}
    set slot 31 of {_i} to paper named "&r&lBUY" with lore "price: %{_price}%"

    set {_slot} to 0
    loop {shop.section.%{_s}%.items::*}:
        set {_info::*} to loop-value split at " && "
        set {_item} to {_info::2} parsed as item

        if {_info::3} is not "-1":
            add "&r&aBuy Price: $%{_info::3}%" to lore of {_item}
        else:
            add "&r&aThis item is not buyable." to lore of {_item}

        if {_info::4} is not "-1":
            add "&r&cSell Price: $%{_info::4}%" to lore of {_item}
        else:
            add "&r&cThis item is not sellable." to lore of {_item}

        add "&r&eLeft click -> Buy" to lore of {_item}
        add "&r&eRight click -> Sell" to lore of {_item}

        add "&8shop-id: %{_info::1}%" to lore of {_item}
        set slot {_slot} of {_i} to {_item}
        add 1 to {_slot}

    open {_i} to {_p}