command /editshop [<text>] [<text>] [<text>] [<text>] [<text>]:
    trigger:
        if arg-1 is "backup":
            set {shop.backup.sections::*} to {shop.sections::*}
            send "&aA backup has been created"



        if arg-1 is "editsection":
            loop {shop.sections::*}:
                set {_info::*} to loop-value split at " && "
                if {_info::3} is arg-2:
                    set {_s} to loop-index

            if {_s} is not set:
                send "&cSection not found!"
                stop

            set {_info::*} to {shop.sections::%{_s}%} split at " && "

            if arg-3 is "slot":
                set {_info::1} to arg-4
            if arg-3 is "item":
                set {_info::2} to arg-4
            if arg-3 is "name":
                set {_info::3} to arg-4
            if arg-3 is "lore":
                set {_info::4} to arg-4
            if arg-3 is "metadata":
                set {_info::5} to arg-4

            set {shop.sections::%{_s}%} to join {_info::*} with " && "

        if arg-1 is "addhanditem":
            loop {shop.sections::*}:
                set {_info::*} to loop-value split at " && "
                if {_info::3} is arg-2:
                    set {_s} to uncolored {_info::3}

            if {_s} is not set:
                send "&cSection not found!"
                stop

            set {_id} to FindAvailableId({_s})
 
            add "%{_id}% && %player's held item% && %arg-3% && %arg-4%" to {shop.section.%{_s}%.items::*}
            send "%player's held item% has been added to {shop.section.%{_s}%.items::*} as id '%{_id}%'"



        if arg-1 is "edititem":
            loop {shop.sections::*}:
                set {_info::*} to loop-value split at " && "
                if {_info::3} is arg-2:
                    set {_s} to uncolored {_info::3}

            if {_s} is not set:
                send "&cSection not found!"
                stop

            loop {shop.section.%{_s}%.items::*}:
                set {_info::*} to loop-value split at " && "
                if {_info::1} is arg-3:
                    set {_id} to loop-index

            set {_info::*} to {shop.section.%{_s}%.items::%{_id}%} split at " && "

            if arg-4 is "buy":
                set {_info::3} to arg-5
            if arg-4 is "sell":
                set {_info::4} to arg-5
            if arg-4 is "delete":
                delete {shop.section.%{_s}%.items::%{_id}%}
            else:
                set {shop.section.%{_s}%.items::%{_id}%} to join {_info::*} with " && "


on tab complete of "/editshop":
    set tab completions for position 1 to "editsection", "backup", "addhanditem", "edititem"

    if tab arg-1 is "editsection":
        loop {shop.sections::*}:
            set {_info::*} to loop-value split at " && "
            add {_info::3} to {_secs::*}
        set tab completions for position 2 to {_secs::*}
        set tab completions for position 3 to "name", "slot", "item", "lore" and "metadata"
    
    if tab arg-1 is "addhanditem":
        loop {shop.sections::*}:
            set {_info::*} to loop-value split at " && "
            add {_info::3} to {_secs::*}
        set tab completions for position 2 to {_secs::*}
        set tab completions for position 3 to "-1"
        set tab completions for position 4 to "-1"

    if tab arg-1 is "edititem":
        loop {shop.sections::*}:
            set {_info::*} to loop-value split at " && "
            add {_info::3} to {_secs::*}
        set tab completions for position 2 to {_secs::*}
        set tab completions for position 3 to "<shop-id>"
        set tab completions for position 4 to "buy", "sell", "delete"


function FindAvailableId(s: text) :: number:
    set {_id} to 0
    while 1 = 1:
        set {_found} to false
        loop {shop.section.%{_s}%.items::*}:
            set {_info::*} to loop-value split at " && "
            if {_info::1} parsed as number is {_id}:
                set {_found} to true
                stop loop
        if {_found} is false:
            return {_id}
        add 1 to {_id}