function OpenSection(p: player, sec: text):
    set {_s} to uncolored {_sec}
    set {_i} to chest inventory with 6 rows named "&8Server Shop » &r%{_s}%"
        
    set {_id} to 0
    loop 54 times:
        set slot {_id} of {_i} to gray stained glass pane named ""
        add 1 to {_id}

    set {_id} to 45
    loop 9 times:
        set slot {_id} of {_i} to light gray stained glass pane named ""
        add 1 to {_id}

    set slot 45 of {_i} to {_p}'s skull named "&r&f%{_p}%" with lore "&aBalance: &r&e%{_p}'s balance%"
    set slot 53 of {_i} to barrier named "&r&cBack"
    set slot 50 of {_i} to arrow named "&r&eNext page >>"
    set slot 48 of {_i} to arrow named "&r&e<< Previous page"

    set {_slot} to 10
    loop {shop.section.%{_s}%.items::*}:
        set {_info::*} to loop-value split at " && "
        set {_item} to {_info::2} parsed as item type

        if {_info::3} is not "-1":
            add "&r&aBuy Price: $%{_info::3}%" to lore of {_item}
        else:
            add "&r&aThis item is not buyable." to lore of {_item}

        if {_info::4} is not "-1":
            add "&r&cSell Price: $%{_info::4}%" to lore of {_item}
        else:
            add "&r&cThis item is not sellable." to lore of {_item}

        add "&r&eLeft click -> Buy" to lore of {_item}
        add "&r&eRight click -> Sell" to lore of {_item}

        add "&8shop-id: %{_info::1}%" to lore of {_item}
        set slot {_slot} of {_i} to {_item}
        add 1 to {_slot}

    open {_i} to {_p}