command /savekit <text>:
    trigger:
        delete {PvPKit.%arg-1%::*}
        if {PvPKit.kits::*} does not contain arg-1:
            add arg-1 to {PvPKit.kits::*}
        loop 36 times:
            set {_slot} to loop-number - 1
            set {_item} to slot {_slot} of player

            set {PvPKit.%arg-1%::%{_slot} + 1%} to {_item}
        send "Kit Saved" to player

command /loadkit <text> [<player>]:
    trigger:
        if arg-2 is set:
            set {_player} to arg-2
        else:
            set {_player} to player
        loop 36 times:
            set {_slot} to loop-number - 1
            set slot {_slot} of {_player} to {PvPKit.%arg-1%::%{_slot} + 1%}
        execute console command "/armor netherite 4 %{_player}%"
        send "Kit loaded." to {_player}
        wait 1 tick
        if arg-1 contains "mace" or "Mace":
            enchant {_player}'s boots with feather falling 4

command /armor <text> [<number>] [<player>]:
    trigger:
        set {_material} to arg-1
        if arg-1 is "netherite":
            set {_armor::1} to netherite helmet
            set {_armor::2} to netherite chestplate
            set {_armor::3} to netherite leggings
            set {_armor::4} to netherite boots


        loop {_armor::*}:
            set level of protection of loop-value to arg-2
            set level of mending of loop-value to 1

        if arg-3 is set:
            set {_p} to arg-3
        else:
            set {_p} to player

        set {_p}'s helmet to {_armor::1}
        set {_p}'s chestplate to {_armor::2}
        set {_p}'s leggings to {_armor::3}
        set {_p}'s boots to {_armor::4}
        set {_p}'s offhand item to shield

on death of player:
    clear drops
    force victim to respawn
    wait 1 tick
    teleport victim to location at 2802, 77, 2930 in world "world"
    execute console command "/loadkit mace %victim%"
    if victim is "EntityZ096x":
        execute console command "/loadkit entitymace %victim%"

on damage of player:
    send "&cDamage: %final damage%" to attacker

command /dummy:
    trigger:
        summon a armor stand at player
        set {_m} to last spawned armor stand

        set {_armor::1} to netherite helmet
        set {_armor::2} to netherite chestplate
        set {_armor::3} to netherite leggings
        set {_armor::4} to netherite boots
        set {_m}'s offhand item to 64 totem of undying

        loop {_armor::*}:
            set level of protection of loop-value to 4
            set level of mending of loop-value to 1

        set {_m}'s helmet to {_armor::1}
        set {_m}'s chestplate to {_armor::2}
        set {_m}'s leggings to {_armor::3}
        set {_m}'s boots to {_armor::4}

command /fucklag:
    trigger:
        loop 2 times:
            loop all entities:
                if loop-entity is not a player:
                    kill loop-entity
            wait 1 tick

command /irongolem:
    trigger:
        summon a iron golem at player
        set {_m} to last spawned iron golem
        set {_m}'s max health to 10000
        set {_m}'s health to 10000
        set {_m}'s offhand item to 64 totem of undying

on damage:
    send action bar "%victim%: %victim's health%" to attacker
    