function center(p: player):
    if 1 = 1:
        set {_yaw} to round((yaw of {_p}) / 90) * 90

        set {_loc} to location of {_p}

        set x-coordinate of {_loc} to floor(x-coordinate of {_loc}) + 0.5
        set z-coordinate of {_loc} to floor(z-coordinate of {_loc}) + 0.5

        set yaw of {_loc} to {_yaw}
        set pitch of {_loc} to 0

        teleport {_p} to {_loc}

command /center:
    trigger:
        set {_item} to stick named "&r&lCenterer"
        give {_item} to player

on right click:
    if player's tool is stick named "&r&lCenterer":
        center(player)